# -*- coding: utf-8 -*-

from BasicSoftwareConst import (OGL_IMPORT, OGL_INTERFACE, OGL_NOTELINK, OGL_SD_MESSAGE, OGL_EXPECTED_STATE, OGL_MODIFY, OGL_CANCEL, OGL_TRY,
                                OGL_PROCESS, OGL_NOTE, OGL_TITLE, OGL_TITLEEND, OGL_STATEMENT, OGL_LOG, OGL_FIXLOG, OGL_FOR, OGL_WHILE)

import pandas as pd

[ID_MNUFILENEWPROJECT, ID_MNUFILEOPEN, ID_MNUFILESAVE, ID_MNUFILESAVEAS, ID_MNUEDITCUT, ID_MNUEDITCOPY, ID_MNUEDITPASTE, ID_MNUFILEPRINTSETUP,
 ID_MNUFILEPRINT, ID_MNUFILEEXPBMP, ID_ARROW, ID_REL_REALISATION, ID_MODIFY, ID_CANCEL, ID_MNUFILEEXPJPG, ID_MNUPROJECTCLOSE,
 ID_NOTE, ID_ACTOR, ID_USECASE, ID_REL_NOTE, ID_IMPORTXML, ID_MNUFILEEXPPNG, ID_MNUFILENEWSEQUENCEDIAGRAM, ID_SD_INSTANCE,
 ID_SD_MESSAGE, ID_ZOOMIN, ID_ZOOMOUT, ID_MNUREDO, ID_MNUUNDO, ID_EXPECTED, ID_STATEMENT, ID_TITLE,
 ID_MAIN_TOOLBAR, ID_SAVEIMAGE, ID_LINK, ID_OTHERLINK, ID_EXPORTPYTHON, ID_NEW_TITLE, ID_END_TITLE, ID_FOR,
 ID_WHILE, ID_TRY, ID_LOG, ID_FIX_INIT, ID_FIX_START, ID_FIX_SETUP, ID_FIX_STOP, ID_FIX_FLUSH, ID_FIX_EXPECT, ID_FIX_ADD,
 ID_FIX_REMOVE, ID_FIX_WAIT, ID_FIXLOG, ID_LOG_DEB, ID_LOG_INF, ID_LOG_WAR, ID_LOG_ERR, ID_LOG_CRI,
 ID_PROCESS, ID_BASICSETUP, ID_SETUPCARO, ID_SETUPSLICE] = range(62)

[ACTION_SELECTOR, ACTION_NEW_ACTOR, ACTION_NEW_FOR, ACTION_NEW_NOTE_LINK, ACTION_NEW_WHILE, ACTION_NEW_STATEMENT, 
 ACTION_NEW_NOTE, ACTION_NEW_TITLE, ACTION_END_TITLE, ACTION_NEW_IMPLEMENT_LINK, ACTION_DEST_IMPLEMENT_LINK,
 ACTION_DEST_NOTE_LINK, ACTION_NEW_MODIFY, ACTION_NEW_TRY, ACTION_NEW_CANCEL, ACTION_DEST_MODIFY, ACTION_DEST_CANCEL,
 ACTION_DEST_TRY, ACTION_FIXLOG_INIT, ACTION_FIXLOG_START, ACTION_FIXLOG_SETUP, ACTION_FIXLOG_STOP, ACTION_FIXLOG_FLUSH,
 ACTION_FIXLOG_EXPECT, ACTION_FIXLOG_ADD, ACTION_FIXLOG_REMOVE, ACTION_FIXLOG_WAIT, ACTION_NEW_IMPORTATION,
 ACTION_LOG_DEB, ACTION_LOG_INF, ACTION_LOG_WAR, ACTION_LOG_ERR, ACTION_LOG_CRI, ACTION_NEW_PROCESS, ACTION_DEST_PROCESS,
 ACTION_ZOOM_IN, ACTION_ZOOM_OUT, ACTION_EXPECTED_STATE, ACTION_AUTO_EXPECTED, ACTION_DEST_EXPECTED, ACTION_NEW_SD_INSTANCE, 
 ACTION_NEW_SD_MESSAGE, ACTION_DST_SD_MESSAGE] = range(43)

ACTIONS = {ID_ARROW             : ACTION_SELECTOR,
           ID_NOTE              : ACTION_NEW_NOTE,
           ID_NEW_TITLE         : ACTION_NEW_TITLE,
           ID_END_TITLE         : ACTION_END_TITLE,
           ID_IMPORTXML         : ACTION_NEW_IMPORTATION,
           ID_REL_REALISATION   : ACTION_NEW_IMPLEMENT_LINK,
           ID_REL_NOTE          : ACTION_NEW_NOTE_LINK,
           ID_ACTOR             : ACTION_NEW_ACTOR,
           ID_FOR               : ACTION_NEW_FOR,
           ID_WHILE             : ACTION_NEW_WHILE,
           ID_STATEMENT         : ACTION_NEW_STATEMENT,
           ID_SD_INSTANCE       : ACTION_NEW_SD_INSTANCE,
           ID_SD_MESSAGE        : ACTION_NEW_SD_MESSAGE,
           ID_ZOOMIN            : ACTION_ZOOM_IN,
           ID_ZOOMOUT           : ACTION_ZOOM_OUT,
           ID_EXPECTED          : ACTION_EXPECTED_STATE,
           ID_MODIFY            : ACTION_NEW_MODIFY,
           ID_CANCEL            : ACTION_NEW_CANCEL,
           ID_TRY               : ACTION_NEW_TRY,
           ID_FIX_INIT          : ACTION_FIXLOG_INIT,
           ID_FIX_START         : ACTION_FIXLOG_START,
           ID_FIX_SETUP         : ACTION_FIXLOG_SETUP,
           ID_FIX_STOP          : ACTION_FIXLOG_STOP,
           ID_FIX_FLUSH         : ACTION_FIXLOG_FLUSH,
           ID_FIX_EXPECT        : ACTION_FIXLOG_EXPECT,
           ID_FIX_ADD           : ACTION_FIXLOG_ADD,
           ID_FIX_REMOVE        : ACTION_FIXLOG_REMOVE,
           ID_FIX_WAIT          : ACTION_FIXLOG_WAIT,
           ID_LOG_DEB           : ACTION_LOG_DEB,
           ID_LOG_INF           : ACTION_LOG_INF,
           ID_LOG_WAR           : ACTION_LOG_WAR,
           ID_LOG_ERR           : ACTION_LOG_ERR,
           ID_LOG_CRI           : ACTION_LOG_CRI,
           ID_PROCESS           : ACTION_NEW_PROCESS
        }

NEXT_ACTIONS = {
        ACTION_SELECTOR             : ACTION_SELECTOR,
        ACTION_NEW_NOTE             : ACTION_SELECTOR,
        ACTION_NEW_IMPORTATION      : ACTION_SELECTOR,
        ACTION_NEW_TITLE            : ACTION_SELECTOR,
        ACTION_END_TITLE            : ACTION_SELECTOR,
        ACTION_NEW_IMPLEMENT_LINK   : ACTION_DEST_IMPLEMENT_LINK,
        ACTION_NEW_NOTE_LINK        : ACTION_DEST_NOTE_LINK,
        ACTION_DEST_IMPLEMENT_LINK  : ACTION_SELECTOR,
        ACTION_DEST_NOTE_LINK       : ACTION_SELECTOR,
        ACTION_NEW_ACTOR            : ACTION_SELECTOR,
        ACTION_NEW_FOR              : ACTION_SELECTOR,
        ACTION_NEW_WHILE            : ACTION_SELECTOR,
        ACTION_NEW_STATEMENT        : ACTION_SELECTOR,
        ACTION_EXPECTED_STATE       : ACTION_DEST_EXPECTED,
        ACTION_AUTO_EXPECTED        : ACTION_DEST_EXPECTED,
        ACTION_NEW_MODIFY           : ACTION_DEST_MODIFY,
        ACTION_NEW_CANCEL           : ACTION_DEST_CANCEL,
        ACTION_NEW_TRY              : ACTION_DEST_TRY,
        ACTION_NEW_SD_INSTANCE      : ACTION_SELECTOR,
        ACTION_NEW_SD_MESSAGE       : ACTION_DST_SD_MESSAGE,
        ACTION_ZOOM_IN              : ACTION_ZOOM_IN,
        ACTION_ZOOM_OUT             : ACTION_ZOOM_OUT,
        ACTION_NEW_PROCESS          : ACTION_DEST_PROCESS}


SOURCE_ACTIONS = [
    ACTION_NEW_IMPLEMENT_LINK,
    ACTION_NEW_NOTE_LINK,
    ACTION_NEW_SD_MESSAGE,
    ACTION_ZOOM_IN,
    ACTION_ZOOM_OUT,
    ACTION_EXPECTED_STATE,
    ACTION_AUTO_EXPECTED,
    ACTION_NEW_MODIFY,
    ACTION_NEW_CANCEL,
    ACTION_NEW_TRY,
    ACTION_NEW_PROCESS
    ]

DEST_ACTIONS  = [
        ACTION_DEST_IMPLEMENT_LINK,
        ACTION_DEST_NOTE_LINK,
        ACTION_DST_SD_MESSAGE,
        ACTION_ZOOM_IN,
        ACTION_ZOOM_OUT,
        ACTION_DEST_EXPECTED,
        ACTION_DEST_MODIFY,
        ACTION_DEST_CANCEL,
        ACTION_DEST_TRY,
        ACTION_DEST_PROCESS]

LINK_TYPE = {
        ACTION_DEST_IMPLEMENT_LINK  :  OGL_INTERFACE,
        ACTION_DEST_NOTE_LINK       :  OGL_NOTELINK, 
        ACTION_DST_SD_MESSAGE       :  OGL_SD_MESSAGE,
        ACTION_DEST_EXPECTED        :  OGL_EXPECTED_STATE,
        ACTION_AUTO_EXPECTED        :  OGL_EXPECTED_STATE,
        ACTION_DEST_MODIFY          :  OGL_MODIFY,
        ACTION_DEST_CANCEL          :  OGL_CANCEL,
        ACTION_DEST_TRY             :  OGL_TRY,
        ACTION_DEST_PROCESS         :  OGL_PROCESS}


OBJECT_LINK = {
        ACTION_NEW_NOTE             : OGL_NOTE, 
        ACTION_NEW_TITLE            : OGL_TITLE, 
        ACTION_END_TITLE            : OGL_TITLEEND,
        ACTION_LOG_DEB              : OGL_LOG, 
        ACTION_LOG_INF              : OGL_LOG,
        ACTION_LOG_WAR              : OGL_LOG,
        ACTION_LOG_ERR              : OGL_LOG,
        ACTION_LOG_CRI              : OGL_LOG,
        ACTION_FIXLOG_INIT          : OGL_FIXLOG, 
        ACTION_FIXLOG_START         : OGL_FIXLOG, 
        ACTION_FIXLOG_SETUP         : OGL_FIXLOG,
        ACTION_FIXLOG_STOP          : OGL_FIXLOG,
        ACTION_FIXLOG_FLUSH         : OGL_FIXLOG,
        ACTION_FIXLOG_EXPECT        : OGL_FIXLOG,
        ACTION_FIXLOG_ADD           : OGL_FIXLOG,
        ACTION_FIXLOG_REMOVE        : OGL_FIXLOG,
        ACTION_FIXLOG_WAIT          : OGL_FIXLOG,
        ACTION_NEW_FOR              : OGL_FOR,
        ACTION_NEW_WHILE            : OGL_WHILE,
        ACTION_NEW_STATEMENT        : OGL_STATEMENT,
        ACTION_NEW_IMPORTATION      : OGL_IMPORT}

df_FIXLOG = pd.DataFrame({ACTION_FIXLOG_INIT : ["Init"], 
                          ACTION_FIXLOG_START : ["Start"], 
                          ACTION_FIXLOG_SETUP : ["Setup"], 
                          ACTION_FIXLOG_STOP : ["Stop"], 
                          ACTION_FIXLOG_FLUSH : ["Flush"],
                          ACTION_FIXLOG_EXPECT : ["Expect"], 
                          ACTION_FIXLOG_ADD : ["Add"], 
                          ACTION_FIXLOG_REMOVE : ["Remove"], 
                          ACTION_FIXLOG_WAIT : ["Wait"]})



df_LOG =  pd.DataFrame({ACTION_LOG_DEB : ["Debug"], 
                        ACTION_LOG_INF : ["Info"], 
                        ACTION_LOG_WAR : ["Warning"], 
                        ACTION_LOG_ERR : ["ERROR"], 
                        ACTION_LOG_CRI : ["Critical"]})

[SCRIPT_MODE, NORMAL_MODE] = range(2)